const collections = [
  {
    id: 1,
    title: 'Computer',
    routeName: 'computer',
    items: [
      {
        id: 10,
        name: 'com2p',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/com2p',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
      },
      {
        id: 110,
        name: 'comp44',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/comp44',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 101,
        name: 'comp55',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/comp55',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 101,
        name: '6comp',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/6comp',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 103,
        name: 'coemp',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/coemp',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 1056,
        name: 'com8p',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/com8p',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
      },
      {
        id: 1024,
        name: 'com533p',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/com533p',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
      },
      {
        id: 1023,
        name: 'com443p',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/computer/com443p',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
      }
    ]
  },
  {
    id: 223,
    title: 'Laptop',
    routeName: 'laptop',
    items: [
      {
        id: 103,
        name: 'comp',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/laptop/comp',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
      },
      {
        id: 1103,
        name: 'comp1',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/laptop/comp1',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 1013,
        name: 'comp2',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/laptop/comp2',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 1013,
        name: 'comp3',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/laptop/comp3',
                breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 1033,
        name: 'comp4',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/laptop/comp4',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 10563,
        name: 'comp5',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        slug: 'shop/laptop/comp5',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,

      },
      {
        id: 10243,
        name: 'comp6',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        slug: 'shop/laptop/comp6',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
        breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
      },
      {
        id: 10233,
        name: 'comp7',
        imageUrl: "https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",

        price: 30,
        slug: 'shop/laptop/comp7',
        breif: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
        description:'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Debitis voluptatem, totam est quia obcaecati earum perspiciatis aperiam quas soluta placeat culpa magni fugit corrupti officiis autem dolores labore minima eos.',
                photos:["https://5.imimg.com/data5/TY/OR/VQ/SELLER-80739298/designer-wallpaper-500x500.jpg",
                "https://www.wallpapertip.com/wmimgs/44-449080_3d-embossed-wallpaper-home-wallpaper-with-price.jpg",
                "https://i.pinimg.com/originals/a8/9e/46/a89e460da924bf69dec53e5494c788e6.jpg",
                "https://sc01.alicdn.com/kf/HTB17C99bcfrK1RjSszcq6xGGFXaX.jpg",
                "https://5.imimg.com/data5/NZ/OB/TC/SELLER-17847209/living-room-wallpaper-500x500.jpg"],
        rating: 5,
      }
    ]
  }
];

export default collections;
